#!/bin/bash

# sysinfo_page - A script to produce an HTML file

cat <<- EOF
    <html>
    <head>
        <title>
        My System Information
        </title>
    </head>

    <body>
    <h1>My System Information</h1>
    </body>
    </html>
EOF
      
